### ISSUE TITLE
Github action build issue

### ISSUE THREAD

**Issue by martonx** [11ty/eleventy-plugin-vite#36] opened 2023-05-31 07:20 UTC
Hi, I have this public repository: https://github.com/martonx/vaporizer

Quite simple 11ty project with vite. But when my Github Actions runs, I got this error:

Run pnpm build

> vaporizer-frontend@0.0.1 build /home/runner/work/vaporizer/vaporizer/Frontend
> npx @11ty/eleventy

[11ty] Writing _site/robots.txt from ./src/robots.txt.njk
[11ty] Writing _site/sitemap.xml from ./src/sitemap.xml.njk
[11ty] Writing _site/arak.html from ./src/arak.njk
[11ty] Writing _site/aszf.html from ./src/aszf.njk
[11ty] Writing _site/index.html from ./src/index.njk
[11ty] Writing _site/Ellenorzes.html from ./src/Ellenorzes.njk
[11ty] Writing _site/rolam.html from ./src/rolam.njk
vite v4.3.8 building for production...
✓ 0 modules transformed.
✓ built in [7](https://github.com/martonx/vaporizer/actions/runs/5129808438/jobs/9227827580#step:6:8)7ms
[vite:build-html] EISDIR: illegal operation on a directory, read
file: /home/runner/work/vaporizer/vaporizer/Frontend/.[11](https://github.com/martonx/vaporizer/actions/runs/5129808438/jobs/9227827580#step:6:12)ty-vite/index.html
[11ty] Encountered a Vite build error, restoring original Eleventy output to _site [Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'PLUGIN_ERROR',
  syscall: 'read',
  pluginCode: 'EISDIR',
  plugin: 'vite:build-html',
  hook: 'transform',
  id: '/home/runner/work/vaporizer/vaporizer/Frontend/.11ty-vite/index.html',
  watchFiles: [
    '/home/runner/work/vaporizer/vaporizer/Frontend/.11ty-vite/arak.html',
    '/home/runner/work/vaporizer/vaporizer/Frontend/.11ty-vite/aszf.html',
    '/home/runner/work/vaporizer/vaporizer/Frontend/.11ty-vite/index.html',
    '/home/runner/work/vaporizer/vaporizer/Frontend/.11ty-vite/Ellenorzes.html',
    '/home/runner/work/vaporizer/vaporizer/Frontend/.11ty-vite/rolam.html'
  ]
}
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] ENOENT: no such file or directory, lstat '/home/runner/work/vaporizer/vaporizer/Frontend/.11ty-vite' (via Error)
[11ty] 
[11ty] Original error stack trace: Error: ENOENT: no such file or directory, lstat '/home/runner/work/vaporizer/vaporizer/Frontend/.11ty-vite'
[11ty] Copied [12](https://github.com/martonx/vaporizer/actions/runs/5129808438/jobs/9227827580#step:6:13) files / Wrote 7 files in 0.[33](https://github.com/martonx/vaporizer/actions/runs/5129808438/jobs/9227827580#step:6:34) seconds (v2.0.1)
transforming...
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.

Here it is my repository: https://github.com/martonx/vaporizer

Please advice, why is it not working?

**Comment by cbcf** [comment] 2023-08-02 22:31
Maybe your issue relates to #15?
Your repo link (https://github.com/martonx/vaporizer) is not working.
Please update if issue persists or consider closing this issue.

**Comment by KiwiKilian** [comment] 2024-06-26 07:03
Closing this one due to no response from the creator. Feel free to comment again if your problem still persists and please provide a publicly available reproduction repository.

**Closed by KiwiKilian** 2024-06-26 07:03 UTC
